
version: '3.8'

services:
  web:
    build: .
    ports:
      - "3847:80"
    depends_on:
      - ms-server
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  ms-server:
    build: ./server
    ports:
      - "9234:8080"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 8080), timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ms_data:
    driver: local

networks:
  default:
    driver: bridge
