// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcjgewxdtevqxleellrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjamdld3hkdGV2cXhsZWVsbHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTE1ODMsImV4cCI6MjA2NTQ2NzU4M30.XkDxfW_xcxwJyn8Kv44pSaPQO8mKjhE5rV8Hr_rhCIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);